/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Controller.EstadosController;
import Models.EstadosModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mateus
 */
public class TelaEstados extends javax.swing.JFrame {

    /**
     * Creates new form TelaEstados
     */
    public TelaEstados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnInserir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSigla = new javax.swing.JTextField();
        txtNomeEstado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnvoltar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEstado = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtNovaSigla = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Insira os dados Abaixo:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 50, 190, 30);

        btnInserir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnInserir.setText(" INSERIR");
        btnInserir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        getContentPane().add(btnInserir);
        btnInserir.setBounds(100, 210, 190, 38);

        btnEditar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEditar.setText("EDITAR UM ESTADO");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(420, 100, 290, 38);

        btnEliminar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete_remove_bin_icon-icons.com_72400.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR UM ESTADO");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(420, 40, 290, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nome do Estado:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 180, 108, 17);

        txtSigla.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtSigla);
        txtSigla.setBounds(220, 130, 130, 31);

        txtNomeEstado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtNomeEstado);
        txtNomeEstado.setBounds(220, 170, 130, 31);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Abreviatura do Estado:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 140, 150, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Você Deseja:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 10, 130, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Estados Já cadastrados: ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 260, 180, 17);

        btnvoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic-back_97586.png"))); // NOI18N
        btnvoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnvoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnvoltarMouseClicked(evt);
            }
        });
        getContentPane().add(btnvoltar);
        btnvoltar.setBounds(22, 10, 60, 30);

        tabelaEstado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ABREVIATURA DO ESTADO", "ESTADO"
            }
        ));
        jScrollPane1.setViewportView(tabelaEstado);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 290, 330, 130);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Nova Abreviatura do Estado:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 100, 200, 20);

        txtNovaSigla.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtNovaSigla);
        txtNovaSigla.setBounds(220, 90, 130, 31);

        setSize(new java.awt.Dimension(740, 482));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(txtSigla.getText().equals("")|| txtSigla == null || txtNomeEstado.getText().equals("") || txtNomeEstado == null || txtNovaSigla.getText().equalsIgnoreCase("") || txtNovaSigla.getText().equalsIgnoreCase(null)){
            JOptionPane.showMessageDialog(null, "Para Atualizar um Estado é necessário inserir os dados acima.");
        }else{
            EstadosModel em = new EstadosModel(txtSigla.getText(), txtNomeEstado.getText());
            EstadosController ec = new EstadosController();
            
            ec.Update(em, txtNovaSigla.getText());
            JOptionPane.showMessageDialog(null, "Estado atualizado com sucesso ");
            
            ArrayList<EstadosModel> lista_em = new ArrayList<>();
           
            lista_em = ec.Index();
            DefaultTableModel dtm = (DefaultTableModel) tabelaEstado.getModel();
            dtm.setRowCount(0);
            tabelaEstado.setModel(dtm);
            
            for(int i =0; i < lista_em.size(); i++){
                dtm.addRow(new Object[]{lista_em.get(i).getSigla(), lista_em.get(i).getNome()});
            }

            tabelaEstado.setModel(dtm);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnvoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvoltarMouseClicked
        // TODO add your handling code here:
        
         this.dispose();
        
    }//GEN-LAST:event_btnvoltarMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(txtSigla.getText().equals("")|| txtSigla == null){
            JOptionPane.showMessageDialog(null, "Para remover um Estado é necessário inserir os dados ao lado.");
        }
        else{
            EstadosModel em = new EstadosModel(txtSigla.getText(), null);
            EstadosController ec = new EstadosController();
            
            ec.Destroy(em);
            JOptionPane.showMessageDialog(null, "Estado deletado com sucesso ");
            
            ArrayList<EstadosModel> lista_em = new ArrayList<>();
           
            lista_em = ec.Index();
            DefaultTableModel dtm = (DefaultTableModel) tabelaEstado.getModel();
            dtm.setRowCount(0);
            tabelaEstado.setModel(dtm);
            
            for(int i =0; i < lista_em.size(); i++){
                dtm.addRow(new Object[]{lista_em.get(i).getSigla(), lista_em.get(i).getNome()});
            }

            tabelaEstado.setModel(dtm);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed

        
        txtSigla.requestFocus();
        if(txtSigla.getText().equalsIgnoreCase("")|| txtSigla.getText().equalsIgnoreCase(null) || txtNomeEstado.getText().equalsIgnoreCase("") || txtNomeEstado.getText().equalsIgnoreCase(null)){
            JOptionPane.showMessageDialog(null, "Para Adicionar um Estado é necessário inserir os dados acima.");
        }
        else{
            EstadosModel em = new EstadosModel(txtSigla.getText(), txtNomeEstado.getText());
            EstadosController ec = new EstadosController();
            
            ec.Store(em);
            
            JOptionPane.showMessageDialog(null, "Estado inserido com sucesso ");
            
            ArrayList<EstadosModel> lista_em = new ArrayList<>();
           
            lista_em = ec.Index();
            DefaultTableModel dtm = (DefaultTableModel) tabelaEstado.getModel();
            dtm.setRowCount(0);
            tabelaEstado.setModel(dtm);
            
            for(int i =0; i < lista_em.size(); i++){
                dtm.addRow(new Object[]{lista_em.get(i).getSigla(), lista_em.get(i).getNome()});
            }

            tabelaEstado.setModel(dtm);
        }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ArrayList<EstadosModel> lista_em = new ArrayList<>();
        
        EstadosController ec = new EstadosController();
        lista_em = ec.Index();
        DefaultTableModel dtm = (DefaultTableModel) tabelaEstado.getModel();
        
        for(int i =0; i < lista_em.size(); i++){
            dtm.addRow(new Object[]{lista_em.get(i).getSigla(), lista_em.get(i).getNome()});
        }
        
        tabelaEstado.setModel(dtm);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEstados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JLabel btnvoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaEstado;
    private javax.swing.JTextField txtNomeEstado;
    private javax.swing.JTextField txtNovaSigla;
    private javax.swing.JTextField txtSigla;
    // End of variables declaration//GEN-END:variables
}
